jobs:
  include:
    - stage: test
      language: python
      python:
        - 3.6
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test
    - stage: test
      language: node_js
      node_js:
        - '14'
      before_install:
        - cd frontend
      install:
        - npm ci
      script:
        - npm run build
    - stage: deploy
      language: node_js
      node_js:
        - '14'
      before_script:
        - openssl aes-256-cbc -K $encrypted_something_key -iv $encrypted_something_iv -in deploy/deploy_key.enc -out deploy/deploy_key -d
      script: bash deploy/deploy.sh
notifications:
  email: false
