version: "3.7"

services:
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
            cache_from:
                - "${NGINX_IMAGE}"
        image: "${NGINX_IMAGE}"
        ports:
            - 80:80
            - 443:443
        volumes:
            - static_volume:/app/website/django_static
            - ./docker/nginx/production:/etc/nginx/conf.d
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        depends_on: 
            - backend  
    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            cache_from:
                - "${WEB_IMAGE}"
        image: "${WEB_IMAGE}"
        entrypoint: /app/docker/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/website/django_static
        expose:
            - 8000        

volumes:
    static_volume: {}

